repo:
  scanPath: /home/icy/code/tmp/testrepos
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main
dirs:
  templates: ./legit/templates
  static: ./legit/static
meta:
  title: icy does git
  description: come get your free software
server:
  name: github.com/icyphox/bild
  host: 0.0.0.0
  port: 5555
