services:
  knot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      KNOT_SERVER_HOSTNAME: ${KNOT_SERVER_HOSTNAME}
      KNOT_SERVER_SECRET: ${KNOT_SERVER_SECRET}
      KNOT_SERVER_DB_PATH: "/app/knotserver.db"
      KNOT_REPO_SCAN_PATH: "/home/git/repositories"
    volumes:
      - "./keys:/etc/ssh/keys"
      - "./repositories:/home/git/repositories"
      - "./server:/app"
    ports:
      - "5555:5555"
      - "2222:22"
