[build]
cmd = 'go build -ldflags "-X tangled.sh/tangled.sh/core/knotserver.version=$(git describe --tags --long)" -o .bin/knot ./cmd/knotserver/main.go'
bin = ".bin/knot"
root = "."

exclude_regex = [""]
include_ext = ["go", "templ"]
