when:
  - event: ["push", "pull_request"]
    branch: ["master"]

dependencies:
  nixpkgs:
    - go
    - gcc

env:
  CGO_ENABLED: 1

steps:
  - name: patch static dir
    command: |
       mkdir -p appview/pages/static; touch appview/pages/static/x

  - name: test all
    command: |
       go test -v ./...

